version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: electrosplit_db
    environment:
      POSTGRES_USER: electrosplit
      POSTGRES_PASSWORD: electrosplit123
      POSTGRES_DB: electrosplit_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
